version: "2.1"

services:
  geth:
    # build: ./geth
    image: ethereum/client-go:stable
    command: --rpc --rpcaddr 0.0.0.0 --rpccorsdomain "*" --rpcvhosts "*" --rpcapi "eth,net,web3,admin"
    healthcheck:
      test: geth attach http://127.0.0.1:8545
      interval: 3s
      timeout: 5s
      retries: 5
    ports:
      - 8545:8545
      - 30303:30303
    volumes:
      - geth-vol:/root
  watcher:
    build: ./watcher
    depends_on:
      geth:
        condition: service_healthy
volumes:
  geth-vol:
